Page({
    data:{
        legends:[
            {
                name:'阿卡丽',
                title:'刺客'
            },
            {
                name:'盖伦',
                tilte:'战士'
            },
            {
                name:'亚索',
                title:'风男'
            },
            {
                name:'火男',
                title:'法师'
            }
        ]
    }
})